---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ddclient
    - MOLECULE_NO_LOG: "false"
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: centos6


install:
  # Install test dependencies.
  - pip install ansible molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME mivek.$ROLE_NAME
  - cd mivek.$ROLE_NAME

script:
  # Run test with molecule
  - molecule test

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/